OrdererOrgs:
  - Name: Orderer
    Domain: pharma.net
    EnableNodeOUs: true
    Specs:
      - Hostname: orderer
        SANS:
          - localhost
PeerOrgs:
  - Name: manufacturer
    Domain: manufacturer.pharma.net
    EnableNodeOUs: true
    Template:
      Count: 2
      SANS:
        - localhost
    Users:
      Count: 1
  - Name: distributor
    Domain: distributor.pharma.net
    EnableNodeOUs: true
    Template:
      Count: 2
      SANS:
        - localhost
    Users:
      Count: 1
  - Name: retailer
    Domain: retailer.pharma.net
    EnableNodeOUs: true
    Template:
      Count: 2
      SANS:
        - localhost
    Users:
      Count: 1
  - Name: consumer
    Domain: consumer.pharma.net
    EnableNodeOUs: true
    Template:
      Count: 2
      SANS:
        - localhost
    Users:
      Count: 1
  - Name: transporter
    Domain: transporter.pharma.net
    EnableNodeOUs: true
    Template:
      Count: 2
      SANS:
        - localhost
    Users:
      Count: 1
  